spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recorddb
    username: postgres
    password: recordpass
    driver-class-name: org.postgresql.Driver

    # EC2 보관용
    # url: jdbc:postgresql://3.34.179.255:5432/recorddb
    # username: recorduser
    # password: recordpass
    # driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloud:
  aws:
    # ⚠️ 여기 값들은 전부 환경변수에서 읽힘 (값이 없으면 빈 문자열이 들어가므로 EC2에선 IAM Role 사용 시 이 블록을 아예 지워도 됨)
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: recording-bucket

openai:
  api-key: ${OPENAI_API_KEY}
$